[package]
name = "shorten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web ="4"
nanoid = "0.4.0"
actix-rt = "2"
serde = { version = "1", features = ["derive"] }
reqwest = "0.11"